# Auto-generated by Backstage template 'request-gcp-vm' -- do not hand-edit
# region/machine settings, resubmit the template instead.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = "asia-south1"
}

variable "project_id" {
  type = string
}

resource "google_compute_instance" "robin" {
  name         = "robin"
  machine_type = "e2-medium"
  zone         = "asia-south1-a"

  labels = {
    environment = "dev"
    requester   = ""
    ttl_hours   = "24"
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-12"
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }
}

output "vm_name" {
  value = google_compute_instance.robin.name
}

output "vm_ip" {
  value = google_compute_instance.robin.network_interface[0].access_config[0].nat_ip
}
